name: timebottle
main: ink.nostal.timebottle.TimeBottle
version: ${version}
api-version: ${api}
author: nostalfinals
folia-supported: true
description: A drift bottle plugin for Paper servers.
libraries:
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0"
  - "org.incendo:cloud-paper:2.0.0-beta.4"
  - "org.incendo:cloud-kotlin-coroutines:2.0.0-beta.4"
  - "org.mongodb:mongodb-driver-kotlin-coroutine:5.0.1"
  - "com.github.shynixn.mccoroutine:mccoroutine-folia-api:2.15.0"
  - "com.github.shynixn.mccoroutine:mccoroutine-folia-core:2.15.0"